name = "SysBioRegistry"
uuid = "9220807d-6617-4137-a5ed-9804499f6854"
repo = "https://github.com/damourChris/SysBioRegistry.jl"
description = "A public registry to publish Sysbio related julia packages"

[packages]
12ad8390-0efd-45b7-9ef7-467bf1407207 = { name = "OntoLinker", path = "O/OntoLinker" }
3c35c355-0acb-4572-93be-ae4d2e4cf8bf = { name = "OntologyLookup", path = "O/OntologyLookup" }
479be80e-0d6f-4501-bee0-9ae8a09d31d3 = { name = "ExpressionData", path = "E/ExpressionData" }
66a9c265-a980-407a-b4a0-c883b541b1af = { name = "SynthethicExpressionMixtures", path = "S/SynthethicExpressionMixtures" }
