name = "SysBioRegistry"
uuid = "9220807d-6617-4137-a5ed-9804499f6854"
repo = "https://github.com/damourChris/SysBioRegistry.jl"
description = "A public registry to publish Sysbio related julia packages"

[packages]
096a9847-e673-4c39-b617-2e8bc302fa74 = { name = "GNNCellTypeEstimator", path = "G/GNNCellTypeEstimator" }
12ad8390-0efd-45b7-9ef7-467bf1407207 = { name = "OntoLinker", path = "O/OntoLinker" }
1f77eb72-0729-4ed2-97ea-5821b29540d7 = { name = "EnsemblGeneMapping", path = "E/EnsemblGeneMapping" }
334f4c7f-84a2-4aae-81dd-4d12ececaed7 = { name = "OntologyMapping", path = "O/OntologyMapping" }
3c35c355-0acb-4572-93be-ae4d2e4cf8bf = { name = "OntologyLookup", path = "O/OntologyLookup" }
479be80e-0d6f-4501-bee0-9ae8a09d31d3 = { name = "ExpressionData", path = "E/ExpressionData" }
4ca4c1c6-74a3-4c57-aa75-00a0b5a8f3e5 = { name = "GNNCellTypeReferenceGraph", path = "G/GNNCellTypeReferenceGraph" }
66a9c265-a980-407a-b4a0-c883b541b1af = { name = "SyntheticExpressionMixtures", path = "S/SyntheticExpressionMixtures" }
66aab7ce-4ed8-4c2b-b8f5-3ecb1547f657 = { name = "OntologyTrees", path = "O/OntologyTrees" }
74a80de1-bd6a-4f9a-8ba7-e671a0fc0c09 = { name = "STRINGdb", path = "S/STRINGdb" }
77d1cb5c-3182-408d-9927-e250d8aeeeea = { name = "ProteinMapping", path = "P/ProteinMapping" }
